language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x ./gradlew
- "./gradlew --no-daemon startDb"
install:
- "./gradlew --no-daemon createTestDb"
script:
- "./gradlew --no-daemon check"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload"
  on:
    tags: true
env:
  global:
  - secure: MdguvKoCQD6zuIB5HNyTXiHjqji+WQh76cnD1J1I9kdYYX/DDRGN7IQ8C4cIsJ+qnI9aNpWIy7Q/33MEs6q7b7QuxhmFA80AYe5dTsOC3DX92u1OqThVfJcLiHuTgzGm+9Yj2NOxKhchB4bvUSfe7/irsjWr6JAAA7DRx2s+cf6/gJVvFsU9jT72ZPBPe5Rd4/Z7lQ0xIlHbSTpwx/dODxLCsBr8Drl1GvYbFCDYIlbH9RutZEtCC6H+MTrFp5WQ9dMjwdp9yQzD8Dk7/KfbDR3Lg1mkHosy30MNFJ8zNcExZ08HAlspJKPVkgQziNjU5YuZ64EjmWCBbaY2YhNdc33fmGtAm6DdbefoBKsI0Q5fMETjytuobwwergnCaJnS9kLSKaO5clA+MMH8JOAbmoLrJoSz4qjtF/kXxfBe+qi4t1RIL0m1lr/pPpEW+gupdgLJl2vNY5UU0cAJEa0NcxoOniEvXmDXH9k5C/z7Xb7srBI4a9CrQdakJDOUOA9gWx7F0/bbGkOg/TfvyRRytox3tn7PDWnGFUKYhwkuE7vchktja/jSQgOqIotFgxIg+KVNyg4sLA5U1LSc5QHyZxN2HBb4qdKHYR+ZB48ar4Yaaxh0StS+Q8IL/B4oHTJxsx01p/dBbmMhlHwmmqCJYy6LlkH51PvTGpB7qm5RP1s=
  - secure: IxncnUiYMNydiE1KqXhaltxXNy7tLIfA+YnjKXj5hT+S0dmC/XNsVEzUG5BC0eR4BlAfbuGwVgdZUX8XbKn7WAxerHbungwqZbdmMivI+GVyxra116wAsnQD54QWPdAJUKxt1gzKYJNR+P+g2WgPh22zFiz+WiBhYE4T42Ic9+eNU4z0SR81N2JEFN5VV+JrokUgljjWv8+zPcIBLdCfbHT+gWqCA2NwbpsEplP0LiJQy3NMLyWUaaquMdt53ufXeJoE37NGT2zMOWUDk9sp5hZ1iDyCJpTcyB49EXnGmTwAsPg28B90LUKe4iCj+BqjqZ6a3L5xchHFrETG5tIyQv2opFfirD4yix80D/bIlbwBG7jNAZNK4lhxlmoF9jrxEOPICmG6xAd2QUwS6nEafF/TdP/4nrBqjL+T61mPminCEi2OZldHL3zJDGTeDFugNFVRzTmtLJN2sE+a0mzT1B2k46RqVH9Eo2pQPOGj6Y2UKmmLC83J7dbXtIvM7CeqCstW1jjFQQPSy3SZFsnxplC8MfIwQJN+FqEODfdFjxtpdTG4b7qHfu/BWxXnhEx2YOwSYvlas5zJMZ49Yn0mi/z5ZMjp39c260vpMJD3UlJaBA2XwoMgExgidmE12tbGmtCddTK1vN6C9IB2zPiONtCfp212t3Rcm6IogMyPLdc=
