-- begin DDCL_LOG_ENTRY
alter table DDCL_LOG_ENTRY add constraint FK_DDCL_LOG_ENTRY_LEVEL foreign key (LEVEL_ID) references ddcl_LOG_LEVEL(ID)^
alter table DDCL_LOG_ENTRY add constraint FK_DDCL_LOG_ENTRY_CATEGORY foreign key (CATEGORY_ID) references DDCL_LOG_ENTRY_CATEGORY(ID)^
create index IDX_DDCL_LOG_ENTRY_LEVEL on DDCL_LOG_ENTRY (LEVEL_ID)^
create index IDX_DDCL_LOG_ENTRY_CATEGORY on DDCL_LOG_ENTRY (CATEGORY_ID)^
create index IDX_DDCL_LOG_ENTRY on DDCL_LOG_ENTRY (LOGGABLE)^
-- end DDCL_LOG_ENTRY
-- begin DDCL_LOG_ENTRY_CATEGORY
create index IDX_DDCL_LOG_ENTRY_CATEGORY_CODE on DDCL_LOG_ENTRY_CATEGORY (CODE)^
-- end DDCL_LOG_ENTRY_CATEGORY
-- begin DDCL_LOG_LEVEL
create index IDX_DDCL_LOG_LEVEL_CODE on ddcl_LOG_LEVEL (CODE)^
-- end DDCL_LOG_LEVEL
